python-metar/python-metar

- .coveragerc
- .gitignore
- README
- metar/Datatypes.py
- metar/Metar.py
- metar/Station.py
- tox.ini
I made these changes to `python-metar` in order to continue to use it in a project that we ported to Python 3. 
Also included a tox configuration file to run tests against all versions of Python from 2.6 to 3.4.
> Python 3 compatibility

- README
- tox.ini
Python 3.5 was released since #11 was made. Thanks for merging that pull request!
> Run tests against Python 3.5

- misc/getstation.py
URL:
http://weather.noaa.gov/pub/data/observations/metar/stations
is not working and should be updated to:
http://tgftp.nws.noaa.gov/data/observations/metar/stations
> NOAA URL update

- metar/Metar.py
On a ParserError with unparsed groups it is helpful to also show the metarcode to avoid costly debugging.
> Provide more information on ParserError

- README
I found that the FMH link seems to have died, but in the process of finding a working link found what appears to be the WMO code standards also.
> Updating links for FMH and WMO references

- metar/Metar.py
* This way, a subclass could create its own list of handlers, and the
code would work just fine. This would allow users to create subclasses
that can handle local variations of the Metar spec without changing
the original Metar code.
> Don't reference class attributes as class attributes within methods.

- metar/Metar.py
- test/test_metar.py
should prevent phrases like `sky: overcastcumulonimbus at 1000 feet`
closes #41
> improve sky_conditions string formatting logic

- metar/Metar.py
Pressure should be differentiated between a SLP provided value and one provided by altimeter.
> don't set press on receipt of SLP value

- metar/Metar.py
- test/test_metar.py
> extend Metar constructor `strict` to cover all `ParserError`s

- metar/Metar.py
- test/test_metar.py
I modified the Metar class to track the WMO "COR" code separately from the US report-modifier group, which can also be "COR".
This addresses issue #62
> add support for COR modifier specified in WMO spec

- CHANGELOG.md
- metar/__init__.py
I'd like to cut a release as we have some bugfixes and no-API breaks (that I know of) yet!  So I rolled the version back to 1.7.0.  If @phobson or others object, I won't be upset by it :)
> make 1.7.0 release of python-metar

- README.md
- metar/__init__.py
- setup.py
This just fixes the broken link to the US METAR spec in setup.py.  That doc is now referred to as FMC-H1-2017, and so I updated that, too, in both the README and setup.py
> Fixed references to Federal Meteorological Handbook No.1

- metar/Metar.py
- test/test_metar.py
This fixes #114 by allowing multiple TREND groups to occur. Since I am just starting with understanding and parsing METAR, please check, if this is OK.
This change now also allows for multiple NOSIG indicators. Would this be OK, or should there be a dedicated group for this case?
> Allow for repeated TREND groups

- metar/Metar.py
- test/test_metar.py
This adds the slashes to the runway regex and then handles them in the runway handler to be decoded to -999. Probably it would be good to change this value or catch this as an exception.
> Fix runway not parsing //// See issue #26

- metar/Metar.py
- test/test_metar.py
- For US-sites, default to KT.
- For all others, default to MPS.
closes #139
> set wind speed defaults when no units provided

- metar/Metar.py
- test/test_metar.py
Values for temperature and dew point should be 2 digits only. According to [this comment](https://github.com/python-metar/python-metar/issues/136#issuecomment-822518301) it might be beneficial to allow 1-digit values as well.
This fixes #136 .
> illegal temperature will raise ParserError

- metar/Metar.py
- test/test_metar.py
Add an extra copy of the wind and visibility, to enable parsing of METARs that list wind and visibility after the sky condition groups.
Fixes #147.
> Enable parsing of METARs that list wind and visibility after the sky condition groups.

- metar/Metar.py
- test/test_metar.py
Although sea level pressure (SLP) groups are normally found in the remarks section, in rare cases the SLP group can be found after the altimeter setting. This PR allows enables parsing of METARs that are structured in this way.
Fixes #148.
> Enable parsing of METARs that list sea level pressure after the altimeter setting rather than in the remarks.

- metar/Metar.py
- test/test_metar.py
This fixes #119, based on the [Manual on Codes](https://library.wmo.int/doc_num.php?explnum_id=10235) sections FM 15-XV/FM 16-XV and 15.13.6.
I also had to adapt an existing test case in which the R/SNOCLO runway state group was wrong.
> fix parsing of R/SNOCLO runway state and adapt tests

- metar/Datatypes.py
I suppose this could be considered an API break, but we ourselves have no code touching this codepath.  We'll document it in the changelog and I can take the blame if the community comes with pitchforks.
closes #130
closes #109
refs #110
> remove unused position.getdistance API

- .github/workflows/ci.yml
- README.md
python 3.6 is soon "dead", this adds 3.10 as a test target
> only test on python 3.7-3.10

- .github/workflows/release.yml
Two things about this:
I'm not sure who has the credentials for metar's pypi, but we need to add the username and password as secrets for the repo for this to work.
And while this as worked for me in the recently past, I don't use this a ton. Point is, we won't really know if it works until we cut a release.
> add workflow to create new pypi release w/ each GH release

- test/test_metar.py
closes #165
Test `test_033_parseTime_auto_month` exposes an impossible edge case to account for, that's when parsing a metar without any hard coded year, month values, but days in "the future" for this month, do not exist for the previous month.  Thus this test is impossible on 28 March, since 29 February does not exist.
> test: circumvent a sometimes impossible test

- .github/workflows/ci.yml
- metar/Metar.py
- misc/getstation.py
- test/test_metar.py
- Use `setup-python` GHA to provide python
- Address `utcnow()` deprecation in #175
> Test on python 3.12

- CHANGELOG.md
- metar/__init__.py
I'm sympathetic to cutting a new release so to get ahead of any python 3.12 testing and to fix the type hinting.
> denote METAR 1.11.0 release

- .gitignore
- metar/Datatypes.py
- metar/Metar.py
- metar/Metar.pyi
This PR removes the unused `utcdelta`, which leads to confusion around whether timezones are handled naively or not. 
Even though code-wise this is a small change, I'd suggest a major semver bump to 2.0.0 as it's a breaking change to the Metar constructor.
This has some overlap with https://github.com/python-metar/python-metar/pull/186; however, that PR suggests broader changes to how timezones are handled, and the utcdelta arg is misleading enough that I believe it should be removed regardless of the decision on how to handle zulu time.
> Remove unused/misleading utcdelta

- README.md
- get_report.py
- metar/__init__.py
- misc/getstation
- misc/getstation.py
weather.noaa.gov has been discontinued for a number of moons.
> Update URLs for METAR data
