- metar/Metar.py
Needed to display recent weather (which is exactly the same as present weather and we can use existing method). Is this solution satisfactory?
> Added method to show recent weather as string

- metar/Metar.py
- test/test_metar.py
Added unit test for sky conditions
> Added handling of NSC sky cover factor

- .travis.yml
- .travis_coveragerc
- README
> setup travis-ci and coveralls, add badges to README

- MANIFEST
This will help us include the LICENSE on the conda recipe.
Not required, but recommended.
> add LICENSE file to MANIFEST

- metar/Metar.py
- test/test_metar.py
> properly carry units on runway visual range

- metar/Metar.py
- metar/__init__.py
- setup.py
* set to 1.6.0 to match upcoming release
fixes #50
> centralize specification of package version

- metar/Station.py
here is my attempt to fix issue #60 and in addition a second problem with finding the nsd_cccc.txt file.
> fix datatypes import and loading of station file

- test/test_station.py
This currently fails per #60 and needs PR #61
> add simple metar.Station.station test

- get_report.py
- metar/Datatypes.py
- metar/Metar.py
- metar/Station.py
- metar/__init__.py
- misc/getstation.py
- parse_metar.py
- sample.py
- test/all_tests.py
- test/test_direction.py
- test/test_distance.py
- test/test_metar.py
- test/test_precipitation.py
- test/test_pressure.py
- test/test_speed.py
- test/test_temperature.py
> run python2.7/Tools/scripts/reindent.py over code base

- metar/Metar.py
- test/test_metar.py
> support CLOUD_TYPE of AC and prevent future KeyErrrors on lookup

- metar/Metar.py
- test/test_metar.py
fixes #67, but the WEATHER_RE match is a false positive
> ensure precip_text is defined in Metar.present_weather

- metar/Datatypes.py
- metar/Metar.py
- metar/Station.py
- metar/__init__.py
- misc/getstation.py
- setup.py
if somebody is against any of the individual commits, we can certainly cherry pick here.
> Rollup of misc / non-func code changes

- metar/Datatypes.py
- metar/Metar.py
- test/test_metar.py
> support 1,3,6 hour ice accretion

- metar/Metar.py
- test/test_metar.py
> allow trailing = in METAR code

- sample.py
Split the `_unparsed` object into two to match the Metar class.
> Metar Samples - Split the _unparsed object into two to match the Metar class

- .github/workflows/ci.yml
> pip install codecov

- metar/Datatypes.py
The correct formula has sin²(angle).
> Fix Haversine formula in position class (Datatypes.py)

- metar/Metar.py
- test/test_metar.py
> Added a 'COR AUTO' case for modifier

- metar/Metar.py
- test/test_metar.py
> Fix default runway unit not being meters

- CHANGELOG.md
- metar/__init__.py
> denote release 1.8.0

- test/test_metar.py
> set month,year on test to remove flapping

- .github/workflows/ci.yml
We should be able to test on python 3.11 :)
> CI: add py3.11, drop py3.7

- CHANGELOG.md
- metar/__init__.py
Might as well make a release with the type hints added
> denote 1.10.0 release
